export const SHOW_PROGRESS = "SHOW_PROGRESS"
export const HIDE_PROGRESS = "HIDE_PROGRESS"

export const GET_CATEGORIES_PENDING = "GET_CATEGORIES_PENDING"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE"
